export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const CHANGE_AUTH_DATA = 'CHANGE_AUTH_DATA';
export const AUTH_REQUEST = 'AUTH_REQUEST';